### ISSUE TITLE
Pump issue not finding source block of water.

### ISSUE THREAD

**Issue by Jmari0** [BuildCraft/BuildCraftLibExpressions#1]
![2018-03-05_23 18 49](https://user-images.githubusercontent.com/34179912/37019664-040b51b2-20ce-11e8-830e-c77b4c16aeab.png)
![2018-03-05_23 19 00](https://user-images.githubusercontent.com/34179912/37019668-080b924a-20ce-11e8-8f09-ed1561560450.png)
![2018-03-05_23 29 58](https://user-images.githubusercontent.com/34179912/37019674-0ab09324-20ce-11e8-8fbf-7622d06bb78b.png)

Pump does not remove single source block but still picks up water at a certain distance.
Moving the source further out results in pump not finding water at all but water trailings are underneath pump.

Version 1.11.2
Buildcraft Version 7.99.8.2
Mod List
![screenshot_20180305234033](https://user-images.githubusercontent.com/34179912/37019832-9eb70be8-20ce-11e8-81a6-c1c58a0e5a52.png)

**Comment by AEnterprise** [comment]
thanks for the report but this should be in the main repo: https://github.com/BuildCraft/BuildCraft
